PIXEL_SIZE = 129
ELECTRON_PER_AD_COUNT = 5.48
QE = 0.9
BASE_LEVEL_AD_COUNTS = 138
EM_GAIN = 300

AD_factor = int(QE*EM_GAIN/ELECTRON_PER_AD_COUNT)
dark_pixel = BASE_LEVEL_AD_COUNTS*ELECTRON_PER_AD_COUNT